cmd/topicctl/subcmd/apply.go, cmd/topicctl/subcmd/get.go, examples/local-cluster/topics/topic-default.yaml, pkg/apply/apply.go, pkg/apply/apply_test.go, pkg/check/check_test.go, pkg/cli/cli.go, pkg/cli/repl.go, pkg/config/cluster.go, pkg/config/cluster_test.go, pkg/config/settings.go, pkg/config/settings_test.go, pkg/groups/format.go
This change includes two, minor usability improvements based on user feedback:
1. Show full member IDs when running `get lags` with the `--full` flag
2. Optionally support a floor on retention reductions. If an apply run includes a topic retention time reduction beyond the limit set in `--retention-drop-step-duration`, then only reduce it down by that amount. To get the full retention reduction with this value set, the user is required to run apply multiple times. This value can also be set on a per-cluster basis by adding a `defaultRetentionDropStepDuration` value into the cluster spec.
The second is motivated by some issues we've had inside Segment when doing big retention reductions on large topics. It's off by default but might be useful in other settings.
=> Misc. usability improvements

cmd/topicctl/subcmd/get.go, pkg/cli/cli.go, pkg/cli/command.go, pkg/cli/command_test.go, pkg/cli/repl.go, pkg/version/version.go
This change updates `topicctl get lags` to support sorting the lags by value. The latter is useful when trying to figure out which member partitions are lagging in a large topic.
This change also updates the repl mode to support optional flags so that users can adjust lag sorting and other things directly  without having to use a non-interactive command for these.
Testing completed successfully via installing locally, verifying that new options worked correctly when hitting a kafka cluster.
=> Support sorting member lags by value

.circleci/config.yml, Dockerfile, cmd/topicctl/subcmd/apply.go, cmd/topicctl/subcmd/tail.go, cmd/topicctl/subcmd/tester.go, go.mod, go.sum, pkg/cli/repl.go, pkg/groups/groups.go
This change updates the version of kakfa-go to pick up the `DescribeGroups` fix in https://github.com/segmentio/kafka-go/pull/752. It also updates the go version used in all images to 1.17.
Testing completed successfully via creating a consumer reading from a topic:
```
./build/topicctl tester --broker-addr=localhost:9092 --topic=topic-default`
export KAFKA_VERSION=2.13-2.7.1 ; docker run --network host -it wurstmeister/kafka:$KAFKA_VERSION /opt/kafka_$KAFKA_VERSION/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic-default --group yolken-test-group3 --property print.key=true --property print.timestamp=true --consumer-property 'partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor'
```
and then getting lags for it:
``` …
```
=> Fix describegroups implementation

pkg/config/load.go
There is currently no support for reading environment variables and change the config file accordingly before applying the config. This PR expands the content read from both cluster and topic config files prior to parsing them.
=> Support expanding cluster and topic yaml config files with the system environment

README.md
This change updates the README to include a link to our recent blog post on the topicctl v1 work: https://segment.com/blog/topicctl-v1/.
=> Include link to v1 blog post in README

pkg/apply/extenders/balanced.go, pkg/apply/extenders/balanced_test.go
Prior to this change, topics with partition counts that are not a multiple of the rack count would be unable to be extended, erroring out with this kind of message (in this case trying to expand from 2 to 21 partitions):
```
INFO Trying to add 19 additional partitions consistent with 'any' strategy
ERROR Cannot balance because extra partitions are not a multiple of the number of racks
```
=> allow extending partition count, even if not a multiple of racks

README.md, pkg/apply/apply.go, pkg/apply/assigners/cross_rack.go, pkg/apply/assigners/cross_rack_test.go, pkg/apply/assigners/evaluate.go, pkg/config/topic.go
Using the `any` placement strategy we discovered that partitions can become imbalanced across racks (e.g., having a partition's replicas only in a single rack).  This can happen when you add brokers and then expand the number of partitions in a topic.
So we add a new `cross-rack` placement strategy and associated assigner, to balance partition replicas across different racks.
=> add cross-rack placement strategy & assigner

README.md, cmd/topicctl/subcmd/apply.go, cmd/topicctl/subcmd/bootstrap.go, cmd/topicctl/subcmd/check.go, cmd/topicctl/subcmd/shared.go, go.mod, go.sum, pkg/admin/throttles_test.go, pkg/admin/types_test.go, pkg/admin/zkclient_test.go, pkg/apply/apply_test.go, pkg/apply/assigners/evaluate_test.go, pkg/apply/assigners/testing.go, pkg/apply/extenders/testing.go, pkg/apply/pickers/testing.go, pkg/apply/rebalancers/testing.go, pkg/config/load.go, pkg/config/load_test.go, pkg/config/settings_test.go, pkg/config/testdata/test-cluster/cluster.yaml, pkg/messages/bounds_test.go, pkg/messages/tail_test.go, pkg/version/version.go, pkg/zk/client_test.go
This change includes miscellaneous fixes to how the cluster config interacts with the environment:
1. Make the environment expansion (added in https://github.com/segmentio/topicctl/pull/46) an opt-in feature via the `--expand-env` flag instead of always enabling it. As reported in https://github.com/segmentio/topicctl/issues/53, it can cause issues if there are literal `$`s in any fields.
2. Don't check the SASL mechanism if setting the username or password via the environment; this addresses https://github.com/segmentio/topicctl/issues/54.
This change also includes some other cleanups:
1. Update minimum go version to 1.17
2. Fix installation instructions and add more details on version compatibility to the README
3. Use `assert.Error` and `assert.NoError` in unit tests when checking …
=> Fix cluster config environment interaction

go.mod, go.sum
Fixes CVE-2020-29652 and CVE-2020-9283 (high CVEs) which comes from x-crypto
=> Upgrade golang x crypto

README.md, pkg/config/cluster.go
Since we are using a `shard` field in the cluster definition in a dependent repository, add it here to allow `topicctl check` to succeed.
=> add shard as a supported field in cluster meta config

pkg/admin/brokerclient.go
Allows for compatibility with MSK serverless by using a read API instead of a write API while still verifying cluster version is >2.4.0
fixes #69
=> use read API instead of write API to verify >2.4.0

.github/dependabot.yml
Dependabot security updates make it easier for you to fix vulnerable dependencies in your repository. If you enable this feature, when a Dependabot alert is raised for a vulnerable dependency in the dependency graph of your repository, Dependabot automatically tries to fix it.
[Supported repos and ecosystems](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems)
=> Add Dependabot to fix vulnerable dependencies

README.md, cmd/topicctl/subcmd/apply.go, pkg/apply/apply.go, pkg/version/version.go
Provides `--auto-continue-rebalance` option that will skip prompting after each rebalance round (this is separate from the prompt to start the rebalance, which can be skipped via `--skip-confirm`).
Also added some output to indicate progress via "Balancing round X of Y" output during rebalance.
=> [DP-420] add autocontinue flag for rebalance

cmd/topicctl/subcmd/tail.go, pkg/cli/cli.go, pkg/cli/repl.go, pkg/messages/tail.go, pkg/messages/tail_test.go
We're making increased use of message headers, so it's important that we be able to see them for debugging purposes. 😄
=> added message headers to tail output

pkg/admin/brokerclient.go, pkg/util/error.go
This is basically a copy of the problem found in https://github.com/segmentio/topicctl/pull/103.
I suspect there could be other instances of the same pattern in other places.
Example error:
```
Response contains errors: map[0:[39] Invalid Replica Assignment: the replica assignment is invalid: Replica assignment has brokers that are not alive. Replica list:ArrayBuffer(0), live broker list: Set(1, 2, 3) 1:[39] Invalid Replica Assignment: the replica assignment is invalid: Replica assignment has brokers that are not alive. Replica list: ArrayBuffer(1, 2, 0), live broker list: Set(1, 2, 3) 2:[39] Invalid Replica Assignment: the replica assignment is invalid: Replica assignment has brokers that are not alive. Replica list: ArrayBuffer(2, 0, 1), live broker list: Set(1, 2, 3)]
```
TODO:
=> Handle errors in AlterParitionReassignment client responses

pkg/admin/format.go, pkg/apply/apply.go, pkg/cli/cli.go, pkg/messages/tail.go
* color.FgBlue is hard to read on both dark and light backgrounds; these were globally changed to FgCyan
* a timer was added to track elapsed time of each round of rebalancing
* redundant status output was either recast as DEBUG (eg `Out of sync...`) or consolidated into single lines from multiple (`Applying throttle`)
* additional output elements (topic names, current round progress, etc) were added to or highlighted in output
=> optimizations for readability of 'apply --rebalance' output

pkg/version/version.go
This is an minor release to include [output reformatting](https://github.com/segmentio/topicctl/pull/116)
=> Update version to 1.9.1

cmd/topicctl/subcmd/reset.go
tested locally with the following setup:
p1-------------->[topic-1]
[cg1]__________> c1
[cg2]__________>c2
\____>c3
p2-------------->[topic-2]
[cg3]__________>c4
\____>c5
this change adds the option --partition-offset-map to the reset-offsets command which allows the use to set multiple offsets for a list of partitions simultaneously in the following manner:
--partition-offset-map <part_id_1>=<offset_1>,<part_id_2>=<offset_2>,....
=> Dp 1495 reset offsets command for multiple partitions at once

README.md, cmd/topicctl/subcmd/rebalance.go, pkg/apply/apply.go, pkg/util/progress.go, pkg/util/strings.go, pkg/version/version.go
To rebalance a topic in topicctl, We currently use topicctl apply $topic --rebalance / topicctl apply $topic --rebalance --to-remove . In a production scale Kafka cluster, there is a need to rebalance all topics for a cluster.
- Add new action - rebalance to topicctl. i.e topicctl rebalance
- Print rebalance progress status (stdout) during rebalance. Refer log [timestamp] INFO Rebalance Progress: {}. (Please refer below screenshots for output)
- Rebalance progress information is two fold. overall topic rebalance status and topic rebalance status for each iteration
- expects --cluster-config (i.e cluster.yaml) and --path-prefix (topics folder)
- Uses underlying topicctl pkg/apply to rebalance a topic
- Argument --show-progress-interval  to show rebalance progress in intervals
- Arguments …
=> topicctl new action: rebalance

cmd/topicctl/subcmd/get.go
https://github.com/segmentio/topicctl/pull/148 introduced two new (known) bugs that are fixed in this PR:
1. The debug command broke for the get subcommand. This is due to PersistentPreRun only traversing one level of subcommands. This is a [known issue with cobra](https://github.com/spf13/cobra/issues/252)
2. Zookeeper get commands broke. This [commit](https://github.com/segmentio/topicctl/pull/148/commits/07667ddf64bfbe9383cb2ae9f2f6b548f169f157) closes the adminclient before the function returns with the defer command, which is not what we want to do. We must keep the adminclient open until the end of the command so this PR reverts that commit which added the buggy `getCliRunnerAndCtx` function
Verification:
1. Debug flag fix
Before:
```bash
go run cmd/topicctl/main.go get topics …
```
=> fix issues from get subcmd refactor

pkg/admin/brokerclient_test.go
TestBrokerClientAlterAssignments appears to fail quite often ([1](https://github.com/segmentio/topicctl/actions/runs/6472883702/job/17574399170), [2](https://github.com/segmentio/topicctl/actions/runs/6474554914/job/17579712456)) due to ISRs not shrinking before the test completes. This PR improves the retry check to see if ISRs have shrunk to their expected value
=> stop flaky test failures

.github/workflows/ci.yml
Updating Github CI actions to trigger on pushing to master and for pull requests that target master branch.
=> Remove duplicate Github actions for every PR

pkg/groups/groups.go, pkg/groups/groups_test.go, pkg/messages/bounds.go, pkg/messages/bounds_test.go
Bug fixes for
- Current offsets for topics are off by 1
- Consumer lags are not displayed properly
- Sometimes, getting lags leads to errors - ERROR Group state is dead; check that group ID is valid
Below topicctl actions will have offset fixtures
```
```
=> topicctl bug fix for offsets

cmd/topicctl/subcmd/get.go, pkg/admin/brokerclient.go, pkg/admin/brokerclient_test.go, pkg/admin/client.go, pkg/admin/format.go, pkg/admin/types.go, pkg/admin/zkclient.go, pkg/admin/zkclient_test.go, pkg/cli/cli.go, pkg/version/version.go
topicctl get action currently does not get the Kafka active controller broker id and cluster id
This PR is to implement actions `topicctl get controllerid`  and `topicctl get clusterid` for the Kafka cluster
```
```
```
```
```
```
```
```
- test cases have been implemented for GetControllerID since GetClusterID already has test cases
=> topicctl get action to fetch controllerid and clusterid

.github/workflows/ci.yml
=> test kafka 3.6.0

README.md, cmd/topicctl/subcmd/delete.go
We cannot mark the `resource-pattern-type` flag as required since it was added in later versions of Kafka, so we provide a default value of any that will get ignored in older versions of Kafka
=> [delete acls] add default value for resource pattern type

cmd/topicctl/subcmd/shared.go, pkg/version/version.go
Fixes a bug in the validation for SASL. Currently username and password cannot be provided by the command line
=> fix: sasl validation

cmd/topicctl/subcmd/apply.go, pkg/apply/apply.go
When applying topic's configuration, we'd like to be able avoid failing in case the desired topic's partitions count is smaller than the actual topic's partitions count (on the broker).
We know that Kafka doesn't allow partitions decrease so instead of failing the operation we'd like to
continue without doing anything (and make this operation idempotent, in that aspect).
This is very convenient when trying to apply a batch of topics in which case, we don't want to fail the rest of the batch for one topic that its partitions count configuration is lower than the actual partitions count. (on the broker).
This change is backward compatible, as the default behavior is kept.
=> apply: Allow ignoring a specific error returned from  updatePartitions()

cmd/topicctl/subcmd/apply.go
Up until now, the `apply` command implemented a fail-fast strategy. This means that an attempt to configure a batch of topics (by passing a path to a folder contains a list of topics configurations files) will be terminated upon the first failure (w/o even trying to apply the configuration for the next-in-line topics).
This commit introduces the fail-safe support:
It allows the user to run the `apply` command in a fail-safe manner, which means that instead of failing upon the first failure, we'll simply continue to the next topic configuration, while aggregating all the errors along the way.
Eventually, if there were any errors, all of them will be shown.
=> subcmd/apply: Support fail-safe approach

pkg/config/cluster.go, pkg/version/version.go
Allow adding arbitrary labels to a cluster file, similar to what we can do for topics and ACLs
=> feat: allow cluster labels

README.md, cmd/topicctl/subcmd/bootstrap.go, pkg/cli/cli.go
- We have a tool which runs `topicctl bootstrap`, then `topicctl rebalance` in succession. 
- With this approach we are currently unable to rebalance topics such as `__consumer_offsets` since they are explicitly [not considered for bootstrap](https://github.com/segmentio/topicctl/blob/5bf428a9e5c762a6985e79a6650cff8a9aa3f4a1/pkg/cli/cli.go#L229-L231)
- This change will introduce a new flag which allows us to bootstrap these topic configurations.
- The default will be to continue current behavior of skipping double-underscore topics.
Example usage
```
topicctl bootstrap --cluster-config=... --allow-internal-topics=true --output=./topics/
[2024-05-10 17:26:47]  INFO Writing config to topics/__amazon_msk_canary.yaml
[2024-05-10 17:26:47]  INFO Writing config to topics/__consumer_offsets.yaml …
```
=> add ability to include internal topics in `bootstrap`

pkg/admin/connector.go
Had an error when tried to get offsets of a topic from a cluster with enabled SASL_PLAINTEXT.
Kafka version: 2.13-3.6.1
Topicctl version: v1.17.0
```bash
topicctl get offsets topic-default \
--broker-addr 127.0.0.1:9092 \
--sasl-username username \
--sasl-password password \
--sasl-mechanism plain 
[2024-05-14 18:33:57] ERROR EOF
```
=> fix: set admin.Connector.Dialer.SASLMechanism if TLS isn't enabled

cmd/topicctl/subcmd/shared.go, pkg/admin/connector.go, pkg/admin/zkclient.go, pkg/groups/groups_test.go, pkg/messages/bounds.go, pkg/messages/bounds_test.go, pkg/messages/tail_test.go, pkg/version/version.go
We use conn timeout as a variable of 10s while fetching topic offset message bounds.
This PR removes the conn timeout variable and exposes it as a flag.
NOTE: connTimeout is a shared variable across topicctl
Please refer the screenshot:
=> Conn timeout as flag in topicctl

.github/workflows/ci.yml
This docker image is no longer supported and we need to remove it from CI to get CI to work again
> [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/bitnami/kafka:0.10.2.1 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
Warning: Docker pull failed with exit code 1, back off 2.816 seconds before retry.
=> Remove test010 from ci

docker-compose-auth.yml
docker-compose-auth KAFKA_CFG_SSL_KEYSTORE_LOCATION has been configured incorrectly causing tls connections to fail(9093, 9095 ports)
This PR is a bug fix to change KAFKA_CFG_SSL_KEYSTORE_LOCATION to correct value kafka.keystore.jks
```
STEP-1: Spin up docker-compose
$ docker-compose -f ./docker-compose-auth.yml up -d
STEP-2: Build topicctl
$ go build -o ./build/topicctl -a ./cmd/topicctl
STEP-3: Connect to cluster via auth (brokerAddr: localhost:9095)
$ ./build/topicctl get topics --cluster-config examples/auth/cluster.yaml
[2024-12-06 12:21:37] ERROR tls: first record does not look like a TLS handshake
```
```
STEP-1: Spin up docker-compose
$ docker-compose -f ./docker-compose-auth.yml up -d
STEP-2: Build topicctl
$ go build -o ./build/topicctl -a ./cmd/topicctl
STEP-3: Connect to …
```
=> [DP-2568] - topiccctl keystore bug fix for docker-compose-auth

pkg/admin/zkclient.go
In fact, err is incorrect and should be  `partitionResp.err`
=> fix: fix the wrong error return value

pkg/apply/apply.go
[We already test for this](https://github.com/segmentio/topicctl/blob/3a2269ff468e198617a40b22d456deffc1809d04/pkg/apply/extenders/balanced_test.go#L12) so no additional testing should be needed. It seems like we simply forgot to update this switch statement way back when we added the cross-rack placement strategy
=> fix: allow expanding cross-rack topics

cmd/topicctl/subcmd/shared.go
Several subcommands use a subset of the config options and sasl-secrets-manager was not included there. This should also fix https://github.com/segmentio/topicctl/issues/205
=> fix: add sasl-secrets-manager-arn to shared opts

pkg/config/cluster.go, pkg/version/version.go
Currently, if spec.sasl.secretsManagerArn is defined in a cluster configuration file, it will take precedence over values for sasl-username and sasl-password provided at the command line.
This is contrary to [conventional patterns of precedence](https://github.com/spf13/viper?tab=readme-ov-file#why-viper) where CLI options are highest, followed by env, file, and defaults. Furthermore, in certain contexts (eg tooling automation) it may not be feasible to change the given cluster configuration file, making it impossible to override to a different SASL credential.
This PR corrects this and when *overriding* configuration ("overriding", according to topicctl, occurs via CLI *or* env) for sasl-username and sasl-password, it ensures secretsManagerArn is not used (whether from config file or …
=> fix: honor sasl params at command line over config file
